#! /bin/sh

set -e

. ${srcdir}/common

# all of these should fail, but when '=' or ' ' aren't used consistently
# between the two options, broken popt sets the version to compare to be
# "a=b"
EXPECT_RETURN=1
RESULT=""
run_test --define-variable=a=b --atleast-pkgconfig-version=999.999

EXPECT_RETURN=1
RESULT=""
run_test --define-variable=a=b --atleast-pkgconfig-version 999.999

EXPECT_RETURN=1
RESULT=""
run_test --define-variable a=b --atleast-pkgconfig-version 999.999

EXPECT_RETURN=1
RESULT=""
run_test --define-variable a=b --atleast-pkgconfig-version=999.999
