#! /bin/sh

set -e

. ${srcdir}/common

RESULT="-isystem /system1 -idirafter /after1 -idirafter /after2 -isystem /system2 -I/foo -I/bar"
run_test --cflags special-flags

RESULT="-framework Foo -lsimple -framework Bar"
run_test --libs special-flags
