#! /bin/sh

set -e

. ${srcdir}/common

RESULT="-DPATH2 -DFOO -DPATH1 -I/path/include"
run_test --cflags flag-dup-1 flag-dup-2
run_test --cflags flag-dup-2 flag-dup-1

RESULT="-Wl,--whole-archive --Wl,--no-whole-archive -Xlinker -R /path/lib \
-L/path/lib -lpath2 -lpath1 -lm"
run_test --libs flag-dup-1 flag-dup-2
run_test --libs flag-dup-2 flag-dup-1
