#! /bin/sh

set -e

. ${srcdir}/common

export PKG_CONFIG_SYSROOT_DIR=/sysroot

# MSYS mangles / paths to its own root in windows format. This probably
# means sysroot doesn't work there, but match what pkg-config passes
# back anyway.
[ "$OSTYPE" = msys ] && root=$(cd / && pwd -W) || root=

RESULT=""
run_test --cflags simple

RESULT="-lsimple"
if [ "$list_indirect_deps" = no ]; then
    run_test --libs simple
fi

RESULT="-lsimple -lm"
if [ "$list_indirect_deps" = yes ]; then
    run_test --libs simple
fi
run_test --libs --static simple

RESULT="-I$root/sysroot/public-dep/include"
run_test --cflags public-dep

RESULT="-L$root/sysroot/public-dep/lib -lpublic-dep"
run_test --libs public-dep
