#! /bin/sh

set -e

. ${srcdir}/common

export PKG_CONFIG_SYSROOT_DIR=/sysroot

RESULT=""
run_test --cflags simple

if [ "$list_indirect_deps" = "yes" ]; then
    RESULT="-lsimple -lm"
else
    RESULT="-lsimple"
fi
run_test --libs simple

RESULT="-I/sysroot/public-dep/include"
run_test --cflags public-dep

RESULT="-L/sysroot/public-dep/lib -lpublic-dep"
run_test --libs public-dep
