#! /bin/sh

set -e

. ${srcdir}/common

if [ "$list_indirect_deps" = "yes" ]; then
    RESULT="-lsimple -lm"
else
    RESULT="-lsimple"
fi
run_test --libs simple

RESULT=""
run_test --libs fields-blank
