#! /bin/sh

set -e

. ${srcdir}/common

RESULT=""
run_test --cflags simple

RESULT=""
run_test --cflags fields-blank

RESULT="-DOTHER -I/other/include"
run_test --cflags other

RESULT="-I/other/include"
run_test --cflags-only-I other

RESULT="-DOTHER"
run_test --cflags-only-other other
