#! /bin/sh

set -e

. ${srcdir}/common

RESULT="-I/includedir/"
case ${MACHTYPE} in
*-msys)
    # Make sure path doesn't get mangled on MSYS
    run_test --define-variable=includedir=\\/includedir/ --cflags simple
    ;;
*)
    run_test --define-variable=includedir=/includedir/ --cflags simple
    ;;
esac
